import { DownloadOutlined, ShareAltOutlined } from '@ant-design/icons';
import { Document, Page, Text, View, StyleSheet, PDFDownloadLink } from '@react-pdf/renderer';
import { BribeReport } from '../types';


// PDF Styles
const styles = StyleSheet.create({
  page: {
    padding: 30,
  },
  header: {
    fontSize: 24,
    textAlign: 'center',
    marginBottom: 20,
    fontWeight: 'bold',
  },
  receiptNumber: {
    textAlign: 'right',
    marginBottom: 10,
  },
  divider: {
    borderBottom: '1px solid #000',
    marginVertical: 15,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  label: {
    fontWeight: 'bold',
  },
  footer: {
    marginTop: 30,
    fontSize: 10,
    textAlign: 'center',
  },
});

const ReceiptPDF = ({ report }: { report: BribeReport }) => (
  <Document>
    <Page size="A5" style={styles.page}>
      <Text style={styles.header}>OFFICIAL BRIBE RECEIPT</Text>
      <Text style={styles.receiptNumber}>#{report.reportId}</Text>
      
      <View style={styles.divider} />
      
      <View style={styles.row}>
        <Text style={styles.label}>Department:</Text>
        <Text>{report.department}</Text>
      </View>
      
      <View style={styles.row}>
        <Text style={styles.label}>Amount:</Text>
        <Text>{report.amount.toLocaleString()} PKR</Text>
      </View>
      
      {report.location && (
        <View style={styles.row}>
          <Text style={styles.label}>Location:</Text>
          <Text>{report.location}</Text>
        </View>
      )}
      
      <View style={styles.row}>
        <Text style={styles.label}>Date:</Text>
        <Text>{report.timestamp?.toLocaleDateString()}</Text>
      </View>
      
      <View style={styles.divider} />
      
      <Text style={{ fontStyle: 'italic', marginTop: 10 }}>
        "This receipt is proof of systemic corruption. Share anonymously to fight back."
      </Text>
      
      <Text style={styles.footer}>
        Generated by BribeBuster - No personal data is stored
      </Text>
    </Page>
  </Document>
);


const ReceiptGenerator = ({ report }: { report: BribeReport }) => {

  const handleShare = () => {
  const text = "I reported corruption via BribeBusterApp";
  const url = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(window.location.href)}&quote=${encodeURIComponent(text)}`;
  window.open(url, '_blank', 'width=600,height=400');
};

  return (
    <div className="bg-gray-800 p-6 rounded-lg">
      <h2 className="text-2xl font-bold text-center mb-4">Your Bribe Report Receipt</h2>
      
      <div className="bg-white text-black p-4 rounded mb-6">
        <div className="flex justify-between mb-2">
          <span className="font-bold">Report ID:</span>
          <span>#{report.reportId}</span>
        </div>
        <div className="flex justify-between mb-2">
          <span className="font-bold">Department:</span>
          <span>{report.department}</span>
        </div>
        <div className="flex justify-between mb-2">
          <span className="font-bold">Amount:</span>
          <span>{report.amount.toLocaleString()} PKR</span>
        </div>
        {report.location && (
          <div className="flex justify-between mb-2">
            <span className="font-bold">Location:</span>
            <span>{report.location}</span>
          </div>
        )}
        <div className="flex justify-between">
          <span className="font-bold">Date:</span>
          <span>{report.timestamp?.toLocaleString()}</span>
        </div>
      </div>

      <div className="flex flex-col space-y-3">
        <PDFDownloadLink 
          document={<ReceiptPDF report={report} />} 
          fileName={`bribe-report-${report.reportId}.pdf`}
          className="w-full"
        >
          {({ loading }) => (
            <button 
              className="flex items-center justify-center w-full py-2 px-4 bg-red-600 hover:bg-red-700 text-white rounded-lg"
              disabled={loading}
            >
              <DownloadOutlined className="mr-2" />
              {loading ? 'Preparing PDF...' : 'Download Receipt'}
            </button>
          )}
        </PDFDownloadLink>

        <button 
          onClick={handleShare}
          className="flex items-center justify-center w-full py-2 px-4 bg-blue-600 hover:bg-blue-700 text-white rounded-lg"
        >
          <ShareAltOutlined className="mr-2" />
          Share Anonymously
        </button>
      </div>
    </div>
  );
};

export default ReceiptGenerator; 
